dist: xenial
addons:
  chrome: stable
language: node_js
branches:
  only:
  - master
  - stable
  - release
  - /^v\d+\.\d+\.\d+$/
  - /^(ck|cf|ci)\/epic\/\d+/
  - ci-spike
services:
- xvfb
node_js:
- "14"
cache: yarn
before_install:
- export START_TIME=$( date +%s )
- export COVERALLS_SERVICE_JOB_ID=$( TRAVIS_JOB_ID )
- export COVERALLS_SERVICE_NAME="CKEditor5 code coverage"
- npm i -g yarn
install:
- yarn install
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - COVERALLS_PARALLEL=true
  jobs:
  - TRAVIS_JOB_TYPE=TestsCore
  - TRAVIS_JOB_TYPE=TestsFeatures
  - TRAVIS_JOB_TYPE=Validation
  jobs:
    include:
    - stage: "Checks"
        script: ./scripts/ci/travis-check.js TestsCore
        name: "TestsCore"
      - script: ./scripts/ci/travis-check.js TestsFeatures
        name: "TestsFeatures"
      - script: ./scripts/ci/travis-check.js Validation
        name: "Validation"
    - stage: "Coverage"
        script: echo coverage check
        name: "Coverage"
