dist: xenial
addons:
  chrome: stable
language: node_js
branches:
  only:
  - master
  - stable
  - release
  - /^v\d+\.\d+\.\d+$/
  - /^(ck|cf|ci)\/epic\/\d+/
  - ci-spike
services:
- xvfb
node_js:
- "14"
cache: yarn
before_install:
- export START_TIME=$( date +%s )
- export COVERALLS_SERVICE_JOB_ID=$( TRAVIS_JOB_ID )
- export COVERALLS_SERVICE_NAME="CKEditor5 code coverage"
- npm i -g yarn
install:
- yarn install
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
notifications:
  webhooks: https://coveralls.io/webhook
env:
  global:
  - COVERALLS_PARALLEL=true
  jobs:
    include:
      # Stage 1
      - stage: Checks
        # Script 1
        name: TestsCore
        script: ./scripts/ci/travis-check.js TestsCore
        # Script 2
      - name: TestsFeatures
        script: ./scripts/ci/travis-check.js TestsFeatures
        # Script 3
      - name: Validation
        script: ./scripts/ci/travis-check.js Validation
      # Stage 2
      - stage: Coverage
        # Script 1
        name: Coverage
        script: echo coverage check
