# For more information about this config, see:
# https://yarnpkg.com/configuration/yarnrc

yarnPath: .yarn/releases/yarn-3.2.3.cjs
nodeLinker: node-modules
nmMode: hardlinks-local
compressionLevel: 0
enableGlobalCache: true
enableTelemetry: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
